### ISSUE TITLE
Unsupported object type when running generate_schema_objects

### ISSUE THREAD

**Issue by ilukac** [mghoneimy/php-graphql-oqm#6] opened 2020-03-18 21:50 UTC
Hi there,

Just wanted to try it against eZ Platform GraphQL and got an error. Any ideas what could be the issue?

PHP Fatal error:  Uncaught RuntimeException: Unsupported object type in /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php:139
Stack trace:
#0 /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php(106): GraphQL\SchemaGenerator\SchemaClassGenerator->generateObject('DomainContent', 'INTERFACE')
#1 /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php(155): GraphQL\SchemaGenerator\SchemaClassGenerator->appendQueryObjectFields(Object(GraphQL\SchemaGenerator\CodeGenerator\QueryObjectClassBuilder), 'ContentRelation', Array)
#2 /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php(133): GraphQL\SchemaGenerator\SchemaClassGenerator->generateQueryObject('ContentRelation')
#3 /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php(106): GraphQL\SchemaGenerator\ in /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php on line 139

Fatal error: Uncaught RuntimeException: Unsupported object type in /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php:139
Stack trace:
#0 /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php(106): GraphQL\SchemaGenerator\SchemaClassGenerator->generateObject('DomainContent', 'INTERFACE')
#1 /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php(155): GraphQL\SchemaGenerator\SchemaClassGenerator->appendQueryObjectFields(Object(GraphQL\SchemaGenerator\CodeGenerator\QueryObjectClassBuilder), 'ContentRelation', Array)
#2 /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php(133): GraphQL\SchemaGenerator\SchemaClassGenerator->generateQueryObject('ContentRelation')
#3 /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php(106): GraphQL\SchemaGenerator\ in /vendor/gmostafa/php-graphql-oqm/src/SchemaGenerator/SchemaClassGenerator.php on line 139

**Comment by mghoneimy** [comment] 2020-03-21 22:13
Hi @ilukac ,
The problem is that the API you're trying to generate the schema for has a type of kind "Interface" which is not currently supported by the library.
The types which are currently supported are query types, inout object types, and enum types.
That being said, I think that the schema generator shouldn't stop generating the whole schema if it encounters an "Interface" type.
Does this haopen with you? Does the generator fail at generating the schema when this alpears?

**Comment by ilukac** [comment] 2020-03-22 11:23
It stops :/

Are you able to make it just bypass those that are not supported?

**Comment by mghoneimy** [comment] 2020-03-22 12:58
@ilukac Yes, that shouldn't be hard. I'll fix this problem tonight, add a test for it, and update you when it's released.

**Comment by ilukac** [comment] 2020-03-22 16:54
Great! Thanks! No rush, nothing urgent :)

**Comment by mghoneimy** [comment] 2020-03-22 22:08
@ilukac I just released v1.0.3 containing a fix to the problem where an unsupported type stops your schema from being generated.
That being said, `Interface` type in graphql is not supported yet by this library, so expect the types referencing the interface to be lacking some definitions, such as a missing field selector method because the field was of type interface.
Hope this helps and let me know if this fixes your problem.

**Comment by ilukac** [comment] 2020-03-23 08:46
Wow, that was fast, thanks! :)

I just run the generate and it finished with few notices as you mentioned:
"generating INTERFACE kind is not supported yet"

Should I create a separate issue for the INTERFACE type, just to have it on the list for future?

**Comment by mghoneimy** [comment] 2020-03-23 11:26
Glad to help :D

Yes, please open a new issue for the interface type problem.

I will close this issue now :v:

**Closed by mghoneimy** 2020-03-23 11:26 UTC
